# Generated by Django 3.0.7 on 2020-06-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('artist', models.CharField(max_length=256)),
                ('genre', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
