# Generated by Django 3.0.7 on 2020-06-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicentry',
            name='submitter',
            field=models.CharField(default='null', max_length=256),
            preserve_default=False,
        ),
    ]
