# Generated by Django 3.0.7 on 2020-06-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PublicKeys",
            fields=[
                (
                    "user_id",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("public_key", models.CharField(max_length=8, unique=True)),
            ],
        ),
    ]
